"""Packet envelope builder for Floor 1.

Wraps raw incoming packets in a standardized PacketEnvelope before forwarding
to Floor 2. This is pure operational wrapping — NO interpretation, NO
transformation of the payload content.

Floor 1 rule: ONLY imports from shared/. No floor_2+ imports.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

from junior_aladdin.floor_1_connection.shared_utils import generate_packet_id
from junior_aladdin.shared.types import PacketEnvelope


def build_envelope(
    raw_payload: dict[str, Any],
    source: str,
    feed_type: str,
    connection_id: str,
    source_timestamp: datetime | None = None,
) -> PacketEnvelope:
    """Wrap raw packet data in a standardized PacketEnvelope.

    This is pure operational wrapping. The raw_payload is preserved
    EXACTLY as received — no interpretation, no transformation.

    Args:
        raw_payload: Raw data from the source (e.g., Angel One tick).
        source: Source identifier (e.g., ``"angel_one"``).
        feed_type: Feed type identifier (e.g., ``"spot_tick"``).
        connection_id: Active connection identifier.
        source_timestamp: Optional timestamp from the source.
            Use None if unavailable.

    Returns:
        A fully populated PacketEnvelope with:
        - ``packet_id``: unique per call (generated by ``generate_packet_id``)
        - ``routing_id``: ``{source}::{feed_type}``
        - ``received_at``: current UTC time
        - ``payload``: **exact copy** of raw_payload (unmodified)
    """
    return PacketEnvelope(
        source=source,
        feed_type=feed_type,
        connection_id=connection_id,
        packet_id=generate_packet_id(),
        routing_id=f"{source}::{feed_type}",
        received_at=datetime.now(timezone.utc),
        source_timestamp=source_timestamp,
        payload=raw_payload.copy(),
    )
