"""Floor 5 — Trade Idea Generator (Step 5.10).

Generates structured trade ideas from confluence, market story, and conviction.
This is the bridge between "what do the heads + Captain think" and
"what should we actually do about it."

Architecture rules (see ROADMAP_FLOOR_05):
- Trade idea is generated AFTER conviction is computed
- Trade idea is consumed by trade_class_engine + armed_plan_engine + trade_constructor
- Captain does NOT recalculate quality or confidence — it judges them
- Trade direction is derived from confluence dominant_direction
- Trade class is derived from market story regime + session phase
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from junior_aladdin.floor_5_captain.captain_types import (
    ConfluenceResult,
    ConvictionBand,
    ConvictionScore,
    MarketStory,
    SessionPhase,
    get_aggression_modifier,
)
from junior_aladdin.shared.types import HeadReport, TradeClass


# ── TradeIdea dataclass ─────────────────────────────────────────────────────


@dataclass
class TradeIdea:
    """A structured trade idea generated by Captain.

    This is NOT an execution plan — it is the conceptual outline that feeds
    into trade class assignment, armed plan creation, and trade construction.

    Fields:
        direction: "BUY" or "SELL" derived from confluence dominant direction.
        trade_class_suggestion: Suggested TradeClass based on market context.
        reasoning: Human-readable explanation of why this idea exists.
        supporting_heads: Heads that aligned with the dominant direction.
        opposing_heads: Heads that opposed or expressed caution.
        conviction_band: Current ConvictionBand for context.
        setup_source: Which head(s) provided the primary setup that backs this idea.
        session_phase: Current session phase for context.
        aggression_modifier: Session aggression modifier applied.
        timestamp: When this idea was generated.
    """
    direction: str = ""
    trade_class_suggestion: TradeClass | None = None
    reasoning: str = ""
    supporting_heads: list[str] = field(default_factory=list)
    opposing_heads: list[str] = field(default_factory=list)
    conviction_band: ConvictionBand = ConvictionBand.REJECT
    setup_source: str = ""
    session_phase: SessionPhase = SessionPhase.OPENING
    aggression_modifier: float = 0.0
    timestamp: datetime = field(default_factory=datetime.utcnow)


# ── Regime-to-trade-class mapping ──────────────────────────────────────────

# Maps market regimes to suggested trade classes
# First = most preferred, second = fallback
_REGIME_TRADE_MAP: dict[str, list[TradeClass]] = {
    "TREND_UP": [TradeClass.CONTINUATION, TradeClass.SCALP],
    "TREND_DOWN": [TradeClass.CONTINUATION, TradeClass.SCALP],
    "WEAK_UP": [TradeClass.LIQUIDITY_RECLAIM, TradeClass.OPTIONS_PRESSURE],
    "WEAK_DOWN": [TradeClass.LIQUIDITY_RECLAIM, TradeClass.OPTIONS_PRESSURE],
    "RANGE": [TradeClass.OPTIONS_PRESSURE, TradeClass.SCALP],
    "CHOP": [TradeClass.SCALP],
    "VOLATILE": [TradeClass.REVERSAL],
}

# Session phase overrides for trade class preference
_SESSION_TRADE_OVERRIDES: dict[SessionPhase, TradeClass | None] = {
    SessionPhase.GOLDEN_MORNING: None,           # Use regime default
    SessionPhase.OPENING: TradeClass.LIQUIDITY_RECLAIM,
    SessionPhase.LUNCH: TradeClass.REVERSAL,
    SessionPhase.CLOSING: TradeClass.SCALP,
}


class TradeIdeaGenerator:
    """Generates structured trade ideas from Captain's upstream analysis.

    Combines confluence (direction + alignment), market story (regime +
    bias + session), and conviction (scores + band) into a single
    coherent trade idea that downstream modules can act on.

    Usage::

        generator = TradeIdeaGenerator()
        idea = generator.generate_idea(
            confluence_result=conf_result,
            market_story=story,
            conviction_score=scores,
            timestamp=datetime.utcnow(),
        )
        if idea.direction:
            logger.info(f"Trade idea: {idea.direction} via {idea.trade_class_suggestion}")
    """

    def __init__(self) -> None:
        """Initialize the trade idea generator."""
        pass

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate_idea(
        self,
        confluence_result: ConfluenceResult | None = None,
        market_story: MarketStory | None = None,
        conviction_score: ConvictionScore | None = None,
        psychology_report: HeadReport | None = None,
        timestamp: datetime | None = None,
    ) -> TradeIdea:
        """Generate a trade idea from upstream analysis inputs.

        All parameters are optional — the generator produces a sensible
        default (empty) idea if inputs are missing.

        Args:
            confluence_result: Result from confluence_engine (direction + quality).
            market_story: Current market story from market_story_engine.
            conviction_score: Result from conviction_engine (scores + band).
            psychology_report: Psychology Head report for caution context.
            timestamp: Current UTC timestamp.

        Returns:
            A ``TradeIdea`` dataclass, or an empty idea if no inputs.
        """
        dt = timestamp or datetime.utcnow()

        # Extract direction from confluence
        direction = self._determine_direction(confluence_result)

        # Only proceed with full idea if we have a valid direction
        if not direction:
            return TradeIdea(
                direction="",
                reasoning=self._build_empty_reason(confluence_result, conviction_score),
                timestamp=dt,
            )

        # Determine trade class
        trade_class = self._suggest_trade_class(
            confluence_result=confluence_result,
            market_story=market_story,
        )

        # Extract supporting / opposing heads
        supporting = self._get_supporting_heads(confluence_result)
        opposing = self._get_opposing_heads(confluence_result, psychology_report)

        # Identify the primary setup source
        setup_source = self._identify_setup_source(confluence_result)

        # Get session info
        session_phase = self._get_session_phase(market_story)
        aggression_modifier = self._get_aggression_modifier(market_story)

        # Build reasoning
        band = conviction_score.conviction_band if conviction_score else ConvictionBand.REJECT
        reasoning = self._build_reasoning(
            direction=direction,
            trade_class=trade_class,
            supporting=supporting,
            opposing=opposing,
            market_story=market_story,
            conviction_score=conviction_score,
        )

        return TradeIdea(
            direction=direction,
            trade_class_suggestion=trade_class,
            reasoning=reasoning,
            supporting_heads=supporting,
            opposing_heads=opposing,
            conviction_band=band,
            setup_source=setup_source,
            session_phase=session_phase,
            aggression_modifier=aggression_modifier,
            timestamp=dt,
        )

    # ------------------------------------------------------------------
    # Internal Logic
    # ------------------------------------------------------------------

    def _determine_direction(
        self,
        confluence_result: ConfluenceResult | None,
    ) -> str:
        """Determine trade direction from confluence result.

        Args:
            confluence_result: Confluence result from confluence_engine.

        Returns:
            ``"BUY"`` for BULLISH, ``"SELL"`` for BEARISH, or ``""`` if unclear.
        """
        if confluence_result is None:
            return ""

        direction = confluence_result.dominant_direction
        if direction == "BULLISH":
            return "BUY"
        elif direction == "BEARISH":
            return "SELL"
        return ""

    def _suggest_trade_class(
        self,
        confluence_result: ConfluenceResult | None,
        market_story: MarketStory | None,
    ) -> TradeClass | None:
        """Suggest a trade class based on market regime and session phase.

        Uses the regime-to-trade-class map, then applies session-phase
        overrides.

        Args:
            confluence_result: Confluence result (for quality context).
            market_story: Market story (for regime + session phase).

        Returns:
            Suggested TradeClass, or None if regime is unclear.
        """
        regime = (market_story.regime or "").upper() if market_story else ""
        session = (
            market_story.session_phase
            if market_story and market_story.session_phase
            else SessionPhase.OPENING
        )

        # Check session-phase override first
        session_override = _SESSION_TRADE_OVERRIDES.get(session)
        if session_override is not None:
            return session_override

        # Fall back to regime-based suggestion
        if regime in _REGIME_TRADE_MAP:
            candidates = _REGIME_TRADE_MAP[regime]
            # If confluence quality is very low (< 0.4) and we have a
            # lower-risk option (SCALP), prefer that
            if (
                confluence_result
                and confluence_result.confluence_quality < 0.4
                and TradeClass.SCALP in candidates
            ):
                return TradeClass.SCALP
            return candidates[0]

        return None

    def _get_supporting_heads(
        self,
        confluence_result: ConfluenceResult | None,
    ) -> list[str]:
        """Get heads that support the dominant direction.

        Args:
            confluence_result: Confluence result.

        Returns:
            List of head names supporting the direction.
        """
        if confluence_result is None:
            return []
        return list(confluence_result.aligned_heads)

    def _get_opposing_heads(
        self,
        confluence_result: ConfluenceResult | None,
        psychology_report: HeadReport | None,
    ) -> list[str]:
        """Get heads that oppose the trade or express caution.

        Includes both confluence opposing heads and psychology caution.

        Args:
            confluence_result: Confluence result.
            psychology_report: Psychology Head report.

        Returns:
            List of head names opposing or cautioning.
        """
        opposing: list[str] = []

        if confluence_result:
            opposing.extend(confluence_result.opposing_heads)

        if psychology_report:
            if not psychology_report.trade_allowed:
                opposing.append("Psychology Head (blocked)")
            elif psychology_report.caution_level > 0.5:
                opposing.append(f"Psychology Head (caution: {psychology_report.caution_level:.1f})")
            if psychology_report.trap_pressure:
                opposing.append("Psychology Head (trap pressure)")

        return opposing

    def _identify_setup_source(
        self,
        confluence_result: ConfluenceResult | None,
    ) -> str:
        """Identify the primary setup source head.

        Picks the highest-priority head from the aligned heads list.
        Priority: SMC > ICT > Technical > Options > Macro.

        Args:
            confluence_result: Confluence result.

        Returns:
            Name of the primary setup source head, or empty string.
        """
        if confluence_result is None:
            return ""

        priority = ["SMC Head", "ICT Head", "Technical Head", "Options Head", "Macro Head"]
        for name in priority:
            if name in confluence_result.aligned_heads:
                return name

        if confluence_result.aligned_heads:
            return confluence_result.aligned_heads[0]

        return ""

    def _get_session_phase(
        self,
        market_story: MarketStory | None,
    ) -> SessionPhase:
        """Extract session phase from market story.

        Args:
            market_story: Market story.

        Returns:
            Current SessionPhase, or OPENING as default.
        """
        if market_story and market_story.session_phase:
            return market_story.session_phase
        return SessionPhase.OPENING

    def _get_aggression_modifier(
        self,
        market_story: MarketStory | None,
    ) -> float:
        """Extract aggression modifier from market story's session phase.

        Args:
            market_story: Market story.

        Returns:
            Aggression modifier float.
        """
        if market_story and market_story.session_phase:
            return get_aggression_modifier(market_story.session_phase)
        return get_aggression_modifier(SessionPhase.OPENING)

    def _build_reasoning(
        self,
        direction: str,
        trade_class: TradeClass | None,
        supporting: list[str],
        opposing: list[str],
        market_story: MarketStory | None,
        conviction_score: ConvictionScore | None,
    ) -> str:
        """Build human-readable reasoning for the trade idea.

        Args:
            direction: Trade direction (BUY/SELL).
            trade_class: Suggested trade class.
            supporting: Supporting head names.
            opposing: Opposing head names.
            market_story: Market story for context.
            conviction_score: Conviction scores.

        Returns:
            Human-readable reasoning string.
        """
        parts: list[str] = []

        # Direction + trade class
        class_label = trade_class.value if trade_class else "?"
        parts.append(f"{direction} ({class_label})")

        # Regime context
        if market_story and market_story.regime:
            parts.append(f"Regime: {market_story.regime}")

        # Bias context
        if market_story and market_story.bias:
            parts.append(f"Bias: {market_story.bias}")

        # Conviction
        if conviction_score:
            band = conviction_score.conviction_band.value
            parts.append(f"Conviction: {band} ({conviction_score.conviction_score:.0f})")

        # Supporting heads
        if supporting:
            parts.append(f"Supporting: {', '.join(supporting)}")

        # Opposing heads / cautions
        if opposing:
            parts.append(f"Caution: {', '.join(opposing)}")

        return " | ".join(parts)

    def _build_empty_reason(
        self,
        confluence_result: ConfluenceResult | None,
        conviction_score: ConvictionScore | None,
    ) -> str:
        """Build reason when no direction could be determined.

        Args:
            confluence_result: Confluence result (may be None or neutral).
            conviction_score: Conviction scores (may be None).

        Returns:
            Human-readable reason string.
        """
        reasons: list[str] = ["No trade idea"]

        if confluence_result is None:
            reasons.append("No confluence data")
        elif not confluence_result.dominant_direction:
            reasons.append("No dominant direction")
        elif confluence_result.dominant_direction == "NEUTRAL":
            reasons.append("Neutral confluence")

        if conviction_score:
            band = conviction_score.conviction_band.value
            reasons.append(f"Conviction: {band} ({conviction_score.conviction_score:.0f})")

        return " | ".join(reasons)

    # ------------------------------------------------------------------
    # Utility
    # ------------------------------------------------------------------

    def get_idea_summary(self, idea: TradeIdea) -> dict[str, Any]:
        """Get a structured summary of the trade idea for dashboard/logging.

        Args:
            idea: The TradeIdea to summarize.

        Returns:
            Dict with key idea fields.
        """
        return {
            "direction": idea.direction,
            "trade_class": idea.trade_class_suggestion.value if idea.trade_class_suggestion else "",
            "reasoning": idea.reasoning,
            "supporting_heads": idea.supporting_heads,
            "opposing_heads": idea.opposing_heads,
            "conviction_band": idea.conviction_band.value,
            "setup_source": idea.setup_source,
            "session_phase": idea.session_phase.value,
            "aggression_modifier": idea.aggression_modifier,
            "has_idea": bool(idea.direction),
            "timestamp": idea.timestamp.isoformat() if idea.timestamp else "",
        }
