"""Junior Aladdin — shared types, config, logging, testing utilities."""

from junior_aladdin.shared.errors import (
    JuniorAladdinError,
    ConnectionError,
    ValidationError,
    ConfigurationError,
    ExecutionError,
    MemoryError,
    ContractViolationError,
)

from junior_aladdin.shared.types import (
    MarketPhase,
    SessionType,
    BiasType,
    TrendState,
    HeadState,
    CaptainMood,
    DecisionType,
    TradeClass,
    ExecutionMode,
    DataHealth,
    FreshnessTag,
    Severity,
    LifecycleState,
    MemoryEventFamily,
    FeedType,
    PacketEnvelope,
    SourceHealth,
    HeadReport,
    FloorSummary,
    CaptainDecision,
    ExecutionIntent,
    ArmedPlan,
    DecisionSnapshot,
    MemoryEvent,
    CMSP,
    Floor2Handoff,
)

__all__ = [
    # Errors
    "JuniorAladdinError",
    "ConnectionError",
    "ValidationError",
    "ConfigurationError",
    "ExecutionError",
    "MemoryError",
    "ContractViolationError",
    # Enums
    "MarketPhase",
    "SessionType",
    "BiasType",
    "TrendState",
    "HeadState",
    "CaptainMood",
    "DecisionType",
    "TradeClass",
    "ExecutionMode",
    "DataHealth",
    "FreshnessTag",
    "Severity",
    "LifecycleState",
    "MemoryEventFamily",
    "FeedType",
    # Dataclasses
    "PacketEnvelope",
    "SourceHealth",
    "HeadReport",
    "FloorSummary",
    "CaptainDecision",
    "ExecutionIntent",
    "ArmedPlan",
    "DecisionSnapshot",
    "MemoryEvent",
    "CMSP",
    "Floor2Handoff",
]
